name = 'typo-plus'
license = 'MIT'
licenselink = 'https://github.com/OleMussmann/typo-plus/LICENSE'
description = 'A typo theme extension'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/OleMussmann/typo-plus'

# If you have a running demo of the theme
demosite = 'https://ole.mn'

# Taxonomy terms
tags = [
    "responsive",
    "simple",
    "clean",
    "light",
    "dark",
    "presentations",
    "minimal",
    "personal",
    "portfolio",
]

features = [
    "responsive",
    "presentations",
]

# If the theme has a single author
[author]
  name = 'Ole Mussmann'
  homepage = 'https://ole.mn'
